CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists items (
id BIGINT generated by default as identity not null,
name VARCHAR(255) not null,
description VARCHAR(255) not null,
available boolean default false,
owner_id integer not null references users(id),
constraint pk_item primary key (id)
);